[package]
name = "disk-hog-backup"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_cmd = "2.0.16"
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
rand = "0.8.5"
tempfile = "3.2"
predicates = "3.1.3"
regex = "1.11.1"
